services:
  backend:
    image: server
    build: ./server
    volumes:
      - type: bind
        source: ${PWD}/server/database.db
        target: /app/database.db

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "backend"